# Generated by Django 4.2.4 on 2023-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_category_options_alter_brand_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ups',
            new_name='upc',
        ),
    ]
