# Generated by Django 4.2.4 on 2023-08-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='negotiator',
        ),
    ]
