# Generated by Django 4.2.4 on 2023-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_negotiator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Negotiator',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
