# Generated by Django 4.2.4 on 2023-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(to='company.product'),
        ),
    ]
