# Generated by Django 4.2.4 on 2023-08-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_products_company_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
