# Generated by Django 4.2.4 on 2023-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(related_name='products', to='company.product'),
        ),
    ]
