# Generated by Django 4.2.4 on 2023-08-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='products',
            new_name='product',
        ),
    ]
